package work.ready.examples.dtx_transaction.model.base;

import work.ready.core.database.Bean;
import work.ready.core.database.Model;

/**
 * Generated by Ready.Work
 */
@SuppressWarnings("serial")
public abstract class BaseDemo<M extends BaseDemo<M>> extends Model<M> implements Bean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}

	public Integer getId() {
		return getInt("id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setGender(Integer gender) {
		set("gender", gender);
		return (M)this;
	}

	public Integer getGender() {
		return getInt("gender");
	}

	public M setAge(Integer age) {
		set("age", age);
		return (M)this;
	}

	public Integer getAge() {
		return getInt("age");
	}

	public M setHeight(Integer height) {
		set("height", height);
		return (M)this;
	}

	public Integer getHeight() {
		return getInt("height");
	}

	public M setWeight(Integer weight) {
		set("weight", weight);
		return (M)this;
	}

	public Integer getWeight() {
		return getInt("weight");
	}

	public M setHobbies(String hobbies) {
		set("hobbies", hobbies);
		return (M)this;
	}

	public String getHobbies() {
		return getStr("hobbies");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}

	public java.util.Date getCreated() {
		return get("created");
	}

	public M setModified(java.util.Date modified) {
		set("modified", modified);
		return (M)this;
	}

	public java.util.Date getModified() {
		return get("modified");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setIsDeleted(Boolean isDeleted) {
		set("isDeleted", isDeleted);
		return (M)this;
	}

	public Boolean getIsDeleted() {
		return get("isDeleted");
	}

	public M setVersion(Integer version) {
		set("version", version);
		return (M)this;
	}

	public Integer getVersion() {
		return getInt("version");
	}

}
