package work.ready.examples.cache.model;

import work.ready.core.database.annotation.Table;
import work.ready.examples.cache.model.base.BaseDemo;

/**
 * Generated by Ready.Work
 */
@Table(tableName = "demo", primaryKey = "id")
public class Demo extends BaseDemo<Demo> {

}
