package work.ready.examples.database.model;

import work.ready.examples.database.model.base.BaseDemo;
import work.ready.core.database.annotation.Table;

/**
 * Generated by Ready.Work
 */
@Table(tableName = "demo", primaryKey = "id")
public class Demo extends BaseDemo<Demo> {

}
