package #(serviceImplPackageName);

import work.ready.core.ioc.annotation.Service;
import #(servicePackageName).#(tableMeta.modelName)Service;
import #(modelPackageName).#(tableMeta.modelName);
import work.ready.core.database.ModelService;

/**
 * Generated by Ready.Work
 */
@Service
public class #(tableMeta.modelName)Service#(firstCharToUpperCase(implName == null ? 'Impl' : implName)) extends ModelService<#(tableMeta.modelName)> implements #(tableMeta.modelName)Service {

}
