package #(servicePackageName);

import work.ready.core.database.Page;
import #(modelPackageName).#(tableMeta.modelName);

import java.util.List;

/**
 * Generated by Ready.Work
 */
public interface #(tableMeta.modelName)Service  {

    #(tableMeta.modelName) createModel();

    #(tableMeta.modelName) findById(Object id);

    List<#(tableMeta.modelName)> findAll();

    boolean deleteById(Object id);

    boolean delete(#(tableMeta.modelName) model);

    Object save(#(tableMeta.modelName) model);

    Object saveOrUpdate(#(tableMeta.modelName) model);

    boolean update(#(tableMeta.modelName) model);

}
